More Env Var examples

diff --git a/.github/workflows/output-job-info.yaml b/.github/workflows/output-job-info.yaml
--- a/.github/workflows/output-job-info.yaml
+++ b/.github/workflows/output-job-info.yaml
@@ -32,6 +32,26 @@ jobs:
       - run: (test -f "${HOME}/.m2/settings.xml" && cat "${HOME}/.m2/settings.xml") || true
       - run: (test -f "${HOME}/.m2/settings2.xml" && cat "${HOME}/.m2/settings2.xml") || echo "File does not exist, safely skipping"
 
-      - run: (test -f "${settings_file}" && cat "${settings_file}") || echo "File does not exist, blerch"
+      - name: The if test Step
+        run: (cat "${HOME}/.m2/settings.xml") || echo "if test is weird, blerch"
+        if: hashFiles('${HOME}/.m2/settings.xml') != ''
+
+      - name: The env-var test Step 1
+        run: (set | grep "${settings_file}") || echo "grep no findy thingy, blerch"
+        env:
+          settings_file: "${HOME}/.m2/settings.xml"
+
+      - name: The env-var test Step 2
+        run: (test -f "${settings_file}" && cat "${settings_file}") || echo "File does not exist, blerch"
+        env:
+          settings_file: "${HOME}/.m2/settings.xml"
+
+      - name: The env-var test Step 3
+        run: echo "${settings_file}"
+        env:
+          settings_file: "${HOME}/.m2/settings.xml"
+
+      - name: The env-var test Step 4
+        run: test -f "${settings_file}" || echo "File not found?"
         env:
           settings_file: "${HOME}/.m2/settings.xml"
